name: docker-buildx
description: Build and Publish docker images using buildx
author: Lenra-io
branding:
  color: blue
  icon: cloud

inputs:
  tags:
    description: The tags to apply to the image, comma separated list of tags
    required: true
  push:
    description: Whether to publish the image or not
    required: false
    default: 'true'
  context:
    description: The docker build context
    required: false
    default: '.'
  dockerfile:
    description: The dockerfile to use
    required: false
    default: 'Dockerfile'
  build-args:
    description: The build arguments to pass to the build
    required: false
    default: ''
  

outputs:
  release-published:
    description: "Whether a release was published or not"
    value: ${{ steps.semantic-release.outputs.new-release-published }}
  release-version:
    description: "The next version discovered by conventional commits"
    value: ${{ steps.semantic-release.outputs.new-release-version }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Publish
      uses: docker/build-push-action@v2
      with:
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        build-args: ${{ inputs.build-args }}
