name: Flutter Build and Test
description: 'Build and test a Flutter app'
author: lenra-io
branding:
  color: orange
  icon: tag

inputs:
  flutter-channel:
    description: 'The release channel of Flutter to use for building and testing'
    required: true
    default: 'stable'
  flutter-version:
    description: 'The version of Flutter to use for building and testing'
    required: true
    default: 'any'

runs:
  using: "composite"
  steps:
  - name: Checkout Code
    uses: actions/checkout@v3

  - name: Setup Flutter Environment
    uses: subosito/flutter-action@v2.10.0
    with:
      channel: ${{ inputs.flutter-version }}
      flutter-version: ${{ inputs.flutter-version }}

  - name: Build and Test Flutter App
    shell: bash
    run: |
      flutter pub get
      flutter test
