name: Mobile App CI/CD

on:
  push:
    branches: 
      - main
      - beta
    paths:
      - 'mobile/**'
      - '!mobile/**/*.md'
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    paths:
      - 'mobile/**'
      - '!mobile/**/*.md'
  workflow_dispatch:

permissions: 
  contents: write
  statuses: write

jobs:
  get-version:
    name: Get Version
    # Call the reusable workflow for getting the version using convco cli.
    uses: lenra-io/github-actions/.github/workflows/get-version.yml@main
    with:
      path: mobile
      changelog-include-hidden-sections: true

  build:
    name: Build Flutter App
    needs: get-version
    if: needs.get-version.outputs.version != '' || github.event_name == 'pull_request'
    # Call the reusable workflow to build the Flutter app using flutter_distributor
    uses: lenra-io/github-actions/.github/workflows/build-flutter.yml@main
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android
            targets: aab
            runner: ubuntu-latest
            artifact-name: android-aab
            artifact-path: dist/android/*.aab
            flutter-build-args: release
          - platform: ios
            targets: ipa
            runner: macos-latest
            artifact-name: ios-ipa
            artifact-path: dist/ios/*.ipa
            flutter-build-args: release,export-method=development
    with:
      working-directory: mobile
      version: ${{ needs.get-version.outputs.version || '0.0.0' }}
      build: ${{ github.run_number }}
      flutter-version: '3.x'
      platform: ${{ matrix.platform }}
      targets: ${{ matrix.targets }}
      runner: ${{ matrix.runner }}
      flutter-build-args: ${{matrix.flutter-build-args}}
      artifact-name: ${{matrix.artifact-name}}
      artifact-path: ${{matrix.artifact-path}}
    secrets:
      UPLOAD_KEY_STORE: ${{ secrets.UPLOAD_KEY_STORE }}
      UPLOAD_KEY_NAME: ${{ secrets.UPLOAD_KEY_NAME }}
      UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
      UPLOAD_STORE_PASSWORD: ${{ secrets.UPLOAD_STORE_PASSWORD }}

  check:
    name: Check Flutter Code
    # Call the reusable workflow that runs code analysis/lint.
    uses: lenra-io/github-actions/.github/workflows/check-flutter.yml@main
    with:
      working-directory: mobile
      flutter-version:  '3.x'

  # pre-coverage-feedback:
  #   name: Prepare for Coverage Feedback
  #   uses: lenra-io/github-actions/.github/workflows/check-run-status.yml@main
  #   with:
  #     name: 'Coverage Report'

  test:
    name: Test Flutter App
    # Call the reusable workflow that runs test and generate a test coverage report into artifacts, artifact's name will be in outputs.
    uses: lenra-io/github-actions/.github/workflows/test-flutter.yml@main
    with:
      working-directory: mobile
      flutter-version:  '3.x'
      artifact-name: coverage

  coverage:
    name: Read Coverage Report
    needs: test
    uses: lenra-io/github-actions/.github/workflows/coverage-report.yml@main
    with:
      with-artifact-name: coverage
      with-artifact-path: lcov.info

  # coverage_feedback:
  #   name: Feedback on Coverage
  #   needs: [pre-coverage-feedback, coverage]
  #   uses: lenra-io/github-actions/.github/workflows/check-run-status.yml@main
  #   if: ${{ needs.pre-coverage-feedback.result && always() }}
  #   with:
  #     check-run-id: ${{ needs.pre-coverage-feedback.outputs.check-run-id }}
  #     name: 'Coverage Report'
  #     status: completed
  #     # Job success or failure
  #     conclusion: ${{ needs.coverage.result }}
  #     output-title: 'Coverage Report'
  #     output-summary: 'Lines coverage at ${{ needs.coverage.outputs.lines-percentage }}% (${{ needs.coverage.outputs.lines-covered }}/${{ needs.coverage.outputs.lines-total }})'
  #     output-text: |
  #       lines......: ${{ needs.coverage.outputs.lines-percentage }}% (${{ needs.coverage.outputs.lines-covered }} of ${{ needs.coverage.outputs.lines-total }} lines)
  #       functions..: ${{ needs.coverage.outputs.functions-percentage }}% (${{ needs.coverage.outputs.functions-covered }} of ${{ needs.coverage.outputs.functions-total }} functions)
  #       branches...:  ${{ needs.coverage.outputs.branches-percentage }}% (${{ needs.coverage.outputs.branches-covered }} of ${{ needs.coverage.outputs.branches-total }} branches)

  release-github:
    name: Release GitHub
    needs: [get-version, build, coverage, check]
    if: needs.get-version.outputs.version != ''
    # Call the reusable workflow to create release to GitHub.
    uses: lenra-io/github-actions/.github/workflows/upsert-release.yml@main
    with:
      version: ${{ needs.get-version.outputs.version }}
      changelog: ${{ needs.get-version.outputs.changelog }}
      prerelease: ${{ needs.get-version.outputs.channel != '' }}
      with-artifact-name: 'ios-ipa'
      with-artifact-path: '*.ipa'

  deploy-playstore:
    name: Deploy to PlayStore
    if: needs.get-version.outputs.version != ''
    needs: [get-version, build, coverage, check]
    # Call the reusable workflow to deploy to the PlayStore using flutter_distributor.
    uses: lenra-io/github-actions/.github/workflows/deploy-flutter.yml@main
    with:
      store: playstore
      package-name: io.lenra.reveel
      with-artifact-name: android
      with-artifact-path: '*.aab'
      playstore-track: alpha
    secrets:
      PLAYSTORE_SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

  deploy-appstore:
    name: Deploy to AppStore
    if: needs.get-version.outputs.version != ''
    needs: [get-version, build, test, check]
    # Call the reusable workflow to deploy to the AppStore using flutter_distributor.
    uses: lenra-io/github-actions/.github/workflows/deploy-flutter.yml@main
    with:
      store: appstore
      with-artifact-name: ios
      with-artifact-path: '*.ipa'
    secrets:
      APPSTORE_USERNAME: ${{ secrets.APPSTORE_USERNAME }}
      APPSTORE_PASSWORD: ${{ secrets.APPSTORE_PASSWORD }}
      APPSTORE_APIKEY: ${{ secrets.APPSTORE_APIKEY }}
      APPSTORE_APIISSUER: ${{ secrets.APPSTORE_APIISSUER }}
