name: publish-to-playstore
description: Publish a new version of the project to the PlayStore
author: shiipou
branding:
  color: green
  icon: tag

inputs:
  service-account:
    description: 'The service account to use to authenticate to the PlayStore'
    required: true
  package-name:
    description: 'The package name of the app to publish'
    required: true
  version:
    description: 'The version to publish'
    required: true
  assets:
    description: 'The path to the release file to publish'
    required: true
  mapping-file:
    description: 'The mapping.txt file used to de-obfuscate your stack traces from crash reports'
    required: false
  track: 
    description: 'The track to publish the release to'
    required: false
    default: 'production'
  changelogs:
    description: 'The changelogs to include in the release'
    required: false
  default-locale:
    description: 'The default locale to use for the changelogs'
    required: false
    default: 'en-US'
runs:
  using: "composite"
  steps:
    - id: changelogs
      uses: actions/github-script@v6
      with:
        github-token: ${{ input.github-token }}
        script: |
          const changelogs = "${{ inputs.changelogs }}"

          """"
          // get localized changelogs from xml
          const changelogsRegex = /<([a-z]{2}-[A-Z]{2})>([\s\S]*?)<\/\1>/g
          const changelogsMap = {}
          let match
          while ((match = changelogsRegex.exec(changelogsXml)) !== null) {
            const locale = match[1]
            const changelog = match[2]
            changelogsMap[locale] = changelog
          }
          
          if (changelogsMap.length == 0) {
            changelogsMap['${{ inputs.default-locale }}'] = changelogs
          }
          core.debug(`changelogsMap=${JSON.stringify(changelogsMap)}`)
          
          return changelogsMap

    - name: write localized changelogs
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs')
          const path = require('path')
          const changelogsDir = 'changelogs'

          const changelogsMap = ${{ steps.changelogs.outputs.result }}

          const locales = Object.keys(changelogsMap)
          core.debug(`locales=${locales}`)

          locales.forEach(locale => {
            const changelog = changelogsMap[locale]
            const changelogPath = path.join(changelogsDir, `whatsnew-${locale}`)
            core.debug(`changelogPath=${changelogPath}`)
            fs.writeFileSync(changelogPath, changelog)
          })
          return changelogsDir

    - id: deploy
      name: Deploy to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ inputs.service-account }}
        packageName: ${{ inputs.package-name }}
        releaseName: ${{ inputs.version }}
        releaseFiles: ${{ inputs.assets }}
        mappingFile: ${{ inputs.mapping-file }}
        track: ${{ inputs.track }}
        whatsNewDirectory: changelogs/
