name: increment-variable
description: Get the next build number for the current build
author: Lenra-io
branding:
  color: orange
  icon: tag

inputs:
  variable-name:
    description: 'Name of the variable value to increment'
    required: true
  dry-run:
    description: "Whether the build-number will be increment or not"
    required: false
    default: 'false'
  github-token:
    description: "The github token to use to update the build number"
    required: true
outputs:
  build-number:
    description: "The next build number to build"
    value: ${{ steps.semantic-release.outputs.new-release-version }}

runs:
  using: "composite"
  steps:
    - id: get-build-number
      name: Get build number
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          const var_name = 'BUILD_NUMBER'
          // Get current build number from github variables
          let build_number = github.rest.actions.getRepoVariable({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: var_name
          })

          if (!buildNumber) {
            buildNumber=1
            if (inputs.dry-run == 'false') {
              github.rest.actions.createRepoVariable({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: var_name,
                value: buildNumber
              });
            }
            return buildNumber
          }

          buildNumber = parseInt(buildNumber) + 1

          if (inputs.dry-run == 'false') {
            github.rest.actions.updateRepoVariable({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: var_name,
              value: buildNumber
            });
          }

          return buildNumber
