name: increment-variable
description: Get the next build number for the current build
author: shiipou
branding:
  color: orange
  icon: tag

inputs:
  variable-name:
    description: 'Name of the variable value to increment'
    required: true
  dry-run:
    description: "Whether the build-number will be increment or not"
    required: false
    default: 'false'
  github-token:
    description: "Github token to use to update the variable"
    required: true
outputs:
  build-number:
    description: "The next build number to build"
    value: ${{ steps.get-build-number.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: increment-variable
      name: Increment Variable
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        result-encoding: string
        script: |
          const var_name = 'BUILD_NUMBER'
          // Get current build number from github variables
          core.debug(`var_name=${var_name}`)
          let buildNumber = await github.request('GET /repos/{owner}/{repo}/actions/variables/{name}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: var_name,
            headers: {
              'X-GitHub-Api-Version': '2022-11-28'
            }
          }).catch(_=> null)
          core.debug(`old_value=${buildNumber}`)
          if (!buildNumber) {
            core.debug(`value didn't exist, creating it to 1`)
            buildNumber=1
            if (inputs.dry-run == 'false') {
              await github.request('POST /repos/{owner}/{repo}/actions/variables', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: var_name,
                value: buildNumber,
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              })
            }
            core.debug(`value=${buildNumber}`)
            return buildNumber
          }

          buildNumber = parseInt(buildNumber) + 1

          core.debug(`value=${value}`)

          if (inputs.dry-run == 'false') {
            await github.request('PATCH /repos/{owner}/{repo}/actions/variables/{name}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: var_name,
              value: buildNumber,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
          }

          return buildNumber
