name: Android keystore
description: 'Will define keystore and key properties for Android signing'
author: lenra-io
branding:
  color: blue
  icon: package

inputs:
  path:
    description: The working directory to run the command in
    required: false
    default: './android/app/key.properties'
  upload-key-store:
    description: The keystore file to sign the app
    required: true
  upload-key-name:
    description: The name of the key to sign the app
    required: true
  upload-store-password:
    description: The password of the keystore
    required: true
  upload-key-password:
    description: The password of the key to sign the app
    required: true

runs:
  using: "composite"
  steps:
  - name: Create ${{ inputs.path }}
    if: ${{ inputs.upload-key-store }}
    shell: bash
    env:
      KEYSTORE: ${{ inputs.upload-key-store }}
    run: |
      keystore_file="$(mktemp)"

      echo "storeFile=$keystore_file" >> ${{ inputs.path}}
      echo "keyAlias=${{ inputs.upload-key-name }}" >> ${{ inputs.path }}
      echo "storePassword=${{ inputs.upload-store-password }}" >> ${{ inputs.path }}
      echo "keyPassword=${{ inputs.upload-key-password }}" >> ${{ inputs.path }}

      echo "$KEYSTORE" | base64 -d > $keystore_file
