name: Android keystore
description: 'Will define keystore and key properties for Android signing'
author: shiipou
branding:
  color: blue
  icon: package

inputs:
  working-directory:
    description: The working directory to run the command in
    required: false
    default: '.'
  upload-key-store:
    description: The keystore file to sign the app
    required: true
  upload-key-name:
    description: The name of the key to sign the app
    required: true
  upload-key-password:
    description: The password of the key to sign the app
    required: true

runs:
  using: "composite"
  steps:
  - name: Create ${{ inputs.working-directory}}/android/key.properties
    if: ${{ inputs.upload-key-store }}
    shell: bash
    env:
      KEYSTORE: ${{ inputs.upload-key-store }}
    run: |
      keystore_file="$(mktemp)"

      echo "storeFile=$keystore_file" >> ${{ inputs.working-directory}}/android/key.properties
      echo "keyAlias=${{ inputs.upload-key-name }}" >> ${{ inputs.working-directory}}/android/key.properties
      echo "storePassword=${{ inputs.upload-key-password }}" >> ${{ inputs.working-directory}}/android/key.properties
      echo "keyPassword=${{ inputs.upload-key-password }}" >> ${{ inputs.working-directory}}/android/key.properties

      echo "$KEYSTORE" | base64 -d > $keystore_file
