name: Workflow use @main version ?

on:
  pull_request:

permissions:
  contents: read

jobs:
  # This workflow will check if no files in `.github/workflows/` contains a line that start with `uses: shiipou/github-actions` and end with the branch from the PR.
  # If it does, it will mark a required check as failed and print all the files that contains the line.
  # It must ignore files in the list of ignored files.
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        env:
          IGNORED_FILES: "${{ vars.ci_ignored_files }}"
        run: |
          branch=$(echo "${{ github.ref_name }}" | sed -e 's/refs\/heads\///g')
          ignore_rules=''
          if [ -n "$IGNORED_FILES" ]; then
            ignore_rules=' | grep -vE "($IGNORED_FILES)"'
          fi
          files=$(grep -lE "uses: shiipou/github-actions/*@${branch}" .github/workflows/* ${ignore_rules}")
          if [ -n "$files" ]; then
            echo "The following files contains an action that uses the @${branch} version instead of @main:"
            echo "$files"
            exit 1
          fi
