name: Release

on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha

permissions:
  contents: write

jobs:
  release:
    needs: get-version
    if: ${{ needs.get-version.outputs.will-release }}
    uses: lenra-io/github-actions/.github/workflows/release.yml@main
    with:
      prerelease-branches: rc,beta,alpha
