name: Release

on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha

permissions:
  contents: write

jobs:
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with:
      prerelease-branches: "^(rc|beta|alpha)$"
  release:
    needs: get-version
    if: ${{ needs.get-version.outputs.will-release }}
    uses: shiipou/github-actions/.github/workflows/release.yml@main
    with:
      version: ${{ needs.get-version.outputs.version }}
      changelogs: ${{ needs.get-version.outputs.changelogs }}
      is-prerelease: ${{ needs.get-version.outputs.is-prerelease }}
