name: Test

on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha

permissions:
  contents: write

jobs:
  get-version:
    uses: lenra-io/github-actions/.github/workflows/get-version.yml@main

  build:
    needs: get-version
    uses: lenra-io/github-actions/.github/workflows/build-elixir.yml@7-task-build-elixir-workflows
    with:
      version: ${{ needs.get-version.outputs.version }}

  release:
    needs: [get-version, build]
    if: ${{ needs.get-version.outputs.will-release }}
    uses: lenra-io/github-actions/.github/workflows/release.yml@main
    with:
      download-artifacts: true
      assets: artifacts/*
