name: Build Docker Image
# description: Build a Docker image with a prebuild artifact included.

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: 'Directory containing the Dockerfile'
        required: false
        default: '.'
      tags:
        type: string
        description: 'Comma separated list of Tag for the docker image'
        required: true
      dockerfile:
        type: string
        description: 'Dockerfile path to use in the docker build command'
        required: false
        default: 'Dockerfile'
      with-artifact-name:
        type: string
        description: 'Name of the artifact to include in the image, can''t be used with with-artifact-ids'
        required: false
      with-artifact-ids:
        type: string
        description: 'Comma separated list of Ids of the artifact to include in the image, can''t be used with with-artifact-name'
        required: false
      with-artifact-unzip:
        type: string
        description: 'Comma separated list of ids or name of downloaded artifact that will be unzip. Default to all artifacts'
        required: false
        default: '*'
      with-artifact-path:
        type: string
        description: 'Where to place the artifacts'
        required: false
        default: 'artifacts/'
      with-artifact-merge:
        type: boolean
        description: 'Whether to merge multiple artifacts into one folder'
        required: false
        default: false

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        if: inputs.with-artifact-name != '' || inputs.with-artifact-ids != ''
        uses: shiipou/download-artifact@main
        with:
          name: ${{ inputs.with-artifact-name }}
          artifact-ids: ${{ inputs.with-artifact-ids }}
          path: ${{ inputs.working-directory }}/${{ inputs.with-artifact-path }}
          unzip: ${{ inputs.with-artifact-unzip }}
          merge-multiple: ${{ inputs.with-artifact-merge }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.working-directory }}/${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
