name: Build Spring Boot App
# description: Build a Spring Boot application and generate a JAR artifact.

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: 'Current Working directory (Useful for mono-repo)'
        required: false
        default: '.'
      version:
        type: string
        description: 'Version to build'
        required: true
      java-version:
        type: string
        description: 'Version of Java to use'
        required: true
        default: '17'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Update version
        run: mvn versions:set -DnewVersion=${{ inputs.version }}

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar
