name: Build Docker Image

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: 'Directory containing the Dockerfile'
        required: false
        default: '.'
      image-name:
        type: string
        description: 'Name of the Docker image to build'
        required: true
      artifact-name:
        type: string
        description: 'Name of the artifact to include in the image'
        required: true
      artifact-path:
        type: string
        description: 'Path pattern to the artifact files'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ inputs.image-name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
