name: Deploy Flutter

on:
  workflow_call:
    inputs:
      flutter-version:
        description: 'Version of Flutter to use'
        required: true
        default: '3.10.0'
      package-name:
        description: 'Package name of the Flutter app'
        required: true
      build-version:
        description: 'Build version to add to the flutter build command'
        required: false
      build-number:
        description: 'The build number must be '
      release-files:
        description: 'Path to the release APK file'
        required: true
    outputs:
      apk-file:
        description: 'Path to the built APK file'
        valueFrom: ${{ steps.build.outputs.apk-file }}
    secrets:
      serviceAccountJsonPlainText:
        description: The token that'll authentificate the user to the GitHub API to create new tags
        required: true

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}

      - name: Get Flutter Packages
        run: flutter pub get
        shell: bash

      - name: Release
        uses: lenra-io/github-actions/jobs/build-flutter@main
        with:
          package-name: ''
          build-version: 0.0.0
          build-number: 0
          release-files: 
