name: Get version

on:
  workflow_call:
    inputs:
      release-branches:
        type: string
        description: The branches on which releases should happen, comma separated name of branches
        required: false
        default: '^(main)$'
      prerelease-branches:
        type: string
        description: The branches on which prereleases should happen, comma separated name of branches
        required: false
        default: '^(rc|beta|alpha)$'
    secrets:
      github-token:
        description: 'The GitHub access token to use to get the next version (needed by semantic release...)'
        required: true
    outputs:
      version:
        description: The version that was released
        value: ${{ jobs.get-version.outputs.version }}
      is-prerelease:
        description: The version that was released
        value: ${{ jobs.get-version.outputs.is-prerelease }}
      changelogs:
        description: The version that was released
        value: ${{ jobs.get-version.outputs.changelogs }}
      will-release:
        description: The version will be released
        value: ${{ jobs.get-version.outputs.will-release }}

permissions:
  contents: read

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      is-prerelease: ${{ steps.get-version.outputs.is-prerelease }}
      changelogs: ${{ steps.get-version.outputs.changelogs }}
      will-release: ${{ steps.get-version.outputs.will-release }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - id: get-version
        name: Release
        uses: lenra-io/github-actions/jobs/release@main
        with:
          dry-run: true
          release-branches: ${{ inputs.release-branches }}
          prerelease-branches: ${{ inputs.prerelease-branches }}
        secrets:
          github-token: ${{ secrets.github-token }}
