name: Get version

on:
  workflow_call:
    inputs:
      release-branches:
        type: string
        description: The branches on which releases should happen, comma separated name of branches
        required: false
        default: 'main'
      prerelease-branches:
        type: string
        description: The branches on which prereleases should happen, comma separated name of branches
        required: false
        default: 'rc,beta,alpha'
    outputs:
      version:
        description: The version that was released
        value: ${{ jobs.get-version.outputs.version }}
jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.VERSION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - id: get-version
        name: Release
        uses: shiipou/github-action/jobs/get-version@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RELEASE_BRANCHES_REGEX: ${{ inputs.release-branches }}
          PRERELEASE_BRANCHES_REGEX: ${{ inputs.prerelease-branches }}
