name: Increment variable

on:
  workflow_call:
    inputs:
      variable-name:
        type: string
        description: 'Name of the variable value to increment'
        required: true
      dry-run: 
        type: boolean
        description: 'If true, the variable will not be updated'
        required: false
        default: false
    secrets:
      token:
        description: 'Override the github token'
        required: false
    outputs:
      value:
        description: The new value of the variable
        value: ${{ jobs.increment.outputs.build-number }}

jobs:
  increment:
    runs-on: ubuntu-latest
    outputs:
      build-number: ${{ steps.get-build-number.outputs.build-number }}
    steps:
      - id: get-build-number
        name: Get build number
        uses: shiipou/github-actions/jobs/increment-variable@1-fix-flutter-release-didnt-work
        with:
          variable-name: ${{ inputs.variable-name }}
          dry-run: ${{ inputs.dry-run }}
          github-token: ${{ secrets.token }}
