name: Release

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'The version to release'
        required: true
      changelogs:
        type: string
        description: 'The changelogs to include in the release'
        required: false
        default: ''
      is-prerelease:
        type: boolean
        description: 'Whether to release a pre-release or not'
        required: false
        default: false
      download-artifacts:
        type: boolean
        description: Whether to download artifacts from previous jobs. If true, the artifacts will be downloaded in the `artifacts/` folder
        required: false
        default: false
      assets:
        type: string
        description: The assets to upload
        required: false
        default: ''

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Downlaod artifacts
        if: ${{ inputs.download-artifacts }}
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Release
        uses: shiipou/github-actions/jobs/release@main
        with:
          version: ${{ inputs.version }}
          changelogs: ${{ inputs.changelogs }}
          pre-release: ${{ inputs.is-prerelease }}
          assets: ${{ inputs.assets }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
