name: Release

on:
  workflow_call:
    inputs:
      release-branches:
        type: string
        description: The branches on which releases should happen, comma separated name of branches
        required: false
        default: 'main'
      prerelease-branches:
        type: string
        description: The branches on which prereleases should happen, comma separated name of branches
        required: false
        default: 'rc,beta,alpha'
      download-artifacts:
        type: boolean
        description: Whether to download artifacts from previous jobs. If true, the artifacts will be downloaded in the `artifacts/` folder
        required: false
        default: false
      assets:
        type: string
        description: The assets to upload
        required: false
        default: ''

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Downlaod artifacts
        if: ${{ inputs.download-artifacts }}
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Release
        uses: lenra-io/github-actions/jobs/release@main
        with:
          release-branches: ${{ inputs.release-branches }}
          prerelease-branches: ${{ inputs.prerelease-branches }}
          assets: ${{ inputs.assets }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
