name: Test Spring Boot App
# description: Run tests and generate coverage report for a Spring Boot application in an artifact.

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: 'Current Working directory (Useful for mono-repo)'
        required: false
        default: '.'
      java-version:
        type: string
        description: 'Version of Java to use'
        required: true
        default: '17'
    outputs:
      artifact-name:
        description: 'Coverage report artifact name'
        value: ${{ jobs.test.outputs.artifact-name }}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    outputs:
      artifact-name: ${{ steps.test.outputs.artifact-name }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Run tests and generate coverage report
        id: test
        run: |
          mvn test jacoco:report
          GENERATED_COVERAGE_NAME="$(mktemp -u -t coverage-XXXX)"
          echo "artifact-name=${GENERATED_COVERAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.test.outputs.artifact-name }}
          path: target/site/jacoco/
